- hosts: all
  vars:
    name: "tr"
    packages:
    - "httpd"
    - "php"
  tasks:
  - name: install package
    package:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"
  - name: Copy content
    copy:
      content: "welcome to do447 test web - test done {{ name }}"
      dest: "/var/www/html/index.php"
  - name: Start the service
    service:
      name: "httpd"
      state: started
  - name: stop service
    service:
      name: "hhtpd"
      state: stopped
    when: "{{ n }}" == "stop"
