- hosts: all
  tasks:
  - name: install package
    package:
      name: "httpd"
      state: present
  - name: Copy content
    copy:
      content: "welcome to do447 test web"
      dest: "/var/www/html/inex.html"
  - name: Start service
    service:
      name: "httpd"
      state: started
